import { defineConfig } from 'tinacms'

const faqFields = [
  { name: 'q', type: 'string' as const, label: 'Question', ui: { component: 'textarea' as const } },
  { name: 'a', type: 'string' as const, label: 'Answer', ui: { component: 'textarea' as const } },
]

const faqListField = {
  name: 'faqs',
  type: 'object' as const,
  list: true,
  label: 'FAQs',
  ui: { itemProps: (item: { q?: string }) => ({ label: item?.q?.slice(0, 60) ?? 'FAQ' }) },
  fields: faqFields,
}

export default defineConfig({
  branch: process.env.GITHUB_BRANCH || process.env.VERCEL_GIT_COMMIT_REF || 'main',
  clientId: process.env.NEXT_PUBLIC_TINA_CLIENT_ID || '',
  token: process.env.TINA_TOKEN || '',
  build: { outputFolder: 'admin', publicFolder: 'public' },
  media: { tina: { mediaRoot: '', publicFolder: 'public' } },
  schema: {
    collections: [
      {
        name: 'siteSettings',
        label: 'Site Settings',
        path: 'content/settings',
        format: 'json',
        match: { include: 'site' },
        ui: { allowedActions: { create: false, delete: false }, global: true },
        fields: [
          { name: 'name', type: 'string', label: 'Business Name' },
          { name: 'legalName', type: 'string', label: 'Legal Name' },
          { name: 'domain', type: 'string', label: 'Domain' },
          { name: 'phone', type: 'string', label: 'Phone (display, e.g. 0406 470 595)' },
          { name: 'phoneTel', type: 'string', label: 'Phone E.164 (e.g. +61406470595)' },
          { name: 'phoneHref', type: 'string', label: 'Phone href (e.g. tel:+61406470595)' },
          { name: 'email', type: 'string', label: 'Email' },
          { name: 'notificationEmail', type: 'string', label: 'Notification Email' },
          { name: 'abn', type: 'string', label: 'ABN' },
          { name: 'licenseNumber', type: 'string', label: 'Licence Number' },
          { name: 'address', type: 'object', label: 'Address', fields: [
            { name: 'street', type: 'string', label: 'Street' },
            { name: 'suburb', type: 'string', label: 'Suburb' },
            { name: 'state', type: 'string', label: 'State' },
            { name: 'postcode', type: 'string', label: 'Postcode' },
            { name: 'country', type: 'string', label: 'Country' },
            { name: 'display', type: 'string', label: 'Full display address' },
          ]},
          { name: 'social', type: 'object', label: 'Social Media', fields: [
            { name: 'facebook', type: 'string', label: 'Facebook URL' },
            { name: 'instagram', type: 'string', label: 'Instagram URL' },
            { name: 'google', type: 'string', label: 'Google Business URL' },
          ]},
          { name: 'pricing', type: 'object', label: 'Pricing Display', fields: [
            { name: 'retrofitFromPerSqm', type: 'number', label: 'Price per m² (number)' },
            { name: 'retrofitFromDisplay', type: 'string', label: 'Price display string' },
          ]},
        ],
      },
      {
        name: 'navigation',
        label: 'Navigation',
        path: 'content/settings',
        format: 'json',
        match: { include: 'nav' },
        ui: { allowedActions: { create: false, delete: false }, global: true },
        fields: [
          { name: 'mainNav', type: 'object', list: true, label: 'Main Nav', ui: { itemProps: (item: { label?: string }) => ({ label: item?.label }) }, fields: [
            { name: 'label', type: 'string', label: 'Label' },
            { name: 'href', type: 'string', label: 'Path' },
          ]},
          { name: 'ctaNav', type: 'object', label: 'CTA Button', fields: [
            { name: 'label', type: 'string', label: 'Label' },
            { name: 'href', type: 'string', label: 'Path' },
          ]},
          { name: 'footerServicesNav', type: 'object', list: true, label: 'Footer: Services', ui: { itemProps: (item: { label?: string }) => ({ label: item?.label }) }, fields: [
            { name: 'label', type: 'string', label: 'Label' },
            { name: 'href', type: 'string', label: 'Path' },
          ]},
          { name: 'footerCompanyNav', type: 'object', list: true, label: 'Footer: Company', ui: { itemProps: (item: { label?: string }) => ({ label: item?.label }) }, fields: [
            { name: 'label', type: 'string', label: 'Label' },
            { name: 'href', type: 'string', label: 'Path' },
          ]},
        ],
      },
      {
        name: 'homePage',
        label: 'Home Page',
        path: 'content/pages',
        format: 'json',
        match: { include: 'home' },
        ui: { allowedActions: { create: false, delete: false }, router: () => '/' },
        fields: [
          { name: 'badge', type: 'string', label: 'Hero Badge' },
          { name: 'headlineWhite', type: 'string', label: 'Headline (white)' },
          { name: 'headlineYellow', type: 'string', label: 'Headline (gold)' },
          { name: 'subtext', type: 'string', label: 'Hero Subtext' },
          { name: 'primaryCtaLabel', type: 'string', label: 'Primary CTA Label' },
          { name: 'adaptorCaption', type: 'string', label: 'Adaptor Caption' },
          { name: 'estimateCtaHeadline', type: 'string', label: 'Estimate CTA Headline' },
          { name: 'estimateCtaSubtext', type: 'string', label: 'Estimate CTA Subtext' },
          { name: 'estimateCtaButtonLabel', type: 'string', label: 'Estimate CTA Button' },
          { name: 'estimateCtaCaption', type: 'string', label: 'Estimate CTA Caption' },
          { name: 'faqHeading', type: 'string', label: 'FAQ Section Heading' },
          { name: 'faqSubheading', type: 'string', label: 'FAQ Section Subheading' },
          { name: 'whyRetrofitEyebrow', type: 'string', label: 'Why Retrofit — Eyebrow' },
          { name: 'whyRetrofitHeading1', type: 'string', label: 'Why Retrofit — Heading Line 1' },
          { name: 'whyRetrofitHeading2', type: 'string', label: 'Why Retrofit — Heading Line 2' },
          {
            name: 'whyRetrofitItems',
            type: 'object',
            list: true,
            label: 'Why Retrofit — Items',
            ui: { itemProps: (item: { headline?: string }) => ({ label: item?.headline ?? 'Item' }) },
            fields: [
              { name: 'iconKey', type: 'string', label: 'Icon', options: [
                { value: 'hammer',       label: 'Hammer' },
                { value: 'layers',       label: 'Layers' },
                { value: 'zap',          label: 'Zap' },
                { value: 'volume2',      label: 'Volume / Sound' },
                { value: 'thermometer',  label: 'Thermometer' },
                { value: 'badgePercent', label: 'Badge / Percent' },
                { value: 'clock',        label: 'Clock' },
                { value: 'shieldCheck',  label: 'Shield / Check' },
                { value: 'star',         label: 'Star' },
                { value: 'wrench',       label: 'Wrench' },
              ]},
              { name: 'headline', type: 'string', label: 'Headline' },
              { name: 'sub', type: 'string', label: 'Subtext', ui: { component: 'textarea' } },
            ],
          },
          {
            name: 'processSteps',
            type: 'object',
            list: true,
            label: 'Process Steps',
            ui: { itemProps: (item: { title?: string }) => ({ label: item?.title ?? 'Step' }) },
            fields: [
              { name: 'title', type: 'string', label: 'Step Title' },
              { name: 'body', type: 'string', label: 'Step Body', ui: { component: 'textarea' } },
              { name: 'callout', type: 'string', label: 'Callout (optional)' },
              { name: 'imageSrc', type: 'image', label: 'Image' },
              { name: 'imageAlt', type: 'string', label: 'Image Alt' },
            ],
          },
          faqListField,
        ],
      },
      {
        name: 'servicesPage',
        label: 'Services Page',
        path: 'content/pages',
        format: 'json',
        match: { include: 'services' },
        ui: { allowedActions: { create: false, delete: false }, router: () => '/services' },
        fields: [
          { name: 'heroHeading', type: 'string', label: 'Hero Heading' },
          { name: 'heroSubtext', type: 'string', label: 'Hero Subtext' },
          { name: 'serviceSections', type: 'object', list: true, label: 'Service Sections',
            ui: { itemProps: (item: { id?: string }) => ({ label: item?.id ?? 'Section' }) },
            fields: [
              { name: 'id', type: 'string', label: 'Anchor ID (do not change)' },
              { name: 'eyebrow', type: 'string', label: 'Eyebrow' },
              { name: 'heading', type: 'string', label: 'Heading' },
              { name: 'bodyText', type: 'string', label: 'Body Text', ui: { component: 'textarea' } },
              { name: 'bullets', type: 'string', list: true, label: 'Bullet Points' },
              { name: 'primaryCta', type: 'object', label: 'Primary CTA', fields: [
                { name: 'label', type: 'string', label: 'Label' },
                { name: 'href', type: 'string', label: 'Path' },
              ]},
              { name: 'secondaryCta', type: 'object', label: 'Secondary CTA (optional)', fields: [
                { name: 'label', type: 'string', label: 'Label' },
                { name: 'href', type: 'string', label: 'Path' },
              ]},
            ],
          },
          { name: 'faqHeading', type: 'string', label: 'FAQ Section Heading' },
          { name: 'faqSubheading', type: 'string', label: 'FAQ Section Subheading' },
          faqListField,
        ],
      },
      {
        name: 'aboutPage',
        label: 'About Page',
        path: 'content/pages',
        format: 'json',
        match: { include: 'about' },
        ui: { allowedActions: { create: false, delete: false }, router: () => '/about' },
        fields: [
          { name: 'heroHeadline', type: 'string', label: 'Hero Headline' },
          { name: 'heroHeadlineYellow', type: 'string', label: 'Hero Headline (gold)' },
          { name: 'heroSubtext', type: 'string', label: 'Hero Subtext', ui: { component: 'textarea' } },
          { name: 'stats', type: 'object', list: true, label: 'Stats', ui: { itemProps: (item: { value?: string }) => ({ label: item?.value }) }, fields: [
            { name: 'value', type: 'string', label: 'Value (e.g. 50+)' },
            { name: 'label', type: 'string', label: 'Label' },
          ]},
          { name: 'storyEyebrow', type: 'string', label: 'Story Eyebrow' },
          { name: 'storyParagraphs', type: 'string', list: true, label: 'Story Paragraphs' },
          { name: 'storyQuote', type: 'string', label: 'Story Quote', ui: { component: 'textarea' } },
        ],
      },
      {
        name: 'contactPage',
        label: 'Contact Page',
        path: 'content/pages',
        format: 'json',
        match: { include: 'contact' },
        ui: { allowedActions: { create: false, delete: false }, router: () => '/contact' },
        fields: [
          { name: 'heroHeadline', type: 'string', label: 'Hero Headline' },
          { name: 'heroSubtext', type: 'string', label: 'Hero Subtext' },
          { name: 'formHeading', type: 'string', label: 'Form Heading' },
          faqListField,
        ],
      },
      {
        name: 'warrantyPage',
        label: 'Warranty Page',
        path: 'content/pages',
        format: 'json',
        match: { include: 'warranty' },
        ui: { allowedActions: { create: false, delete: false }, router: () => '/warranty' },
        fields: [
          { name: 'heroHeadline', type: 'string', label: 'Hero Headline' },
          { name: 'heroHeadlineYellow', type: 'string', label: 'Hero Headline (gold)' },
          { name: 'heroSubtext', type: 'string', label: 'Hero Subtext' },
          { name: 'coveredItems', type: 'object', list: true, label: "What's Covered", ui: { itemProps: (item: { item?: string }) => ({ label: item?.item }) }, fields: [
            { name: 'item', type: 'string', label: 'Item Name' },
            { name: 'detail', type: 'string', label: 'Detail', ui: { component: 'textarea' } },
          ]},
          { name: 'notCoveredItems', type: 'object', list: true, label: "What's Not Covered", ui: { itemProps: (item: { item?: string }) => ({ label: item?.item }) }, fields: [
            { name: 'item', type: 'string', label: 'Item Name' },
            { name: 'detail', type: 'string', label: 'Detail', ui: { component: 'textarea' } },
          ]},
          { name: 'claimSteps', type: 'string', list: true, label: 'Claim Steps' },
          { name: 'ctaHeadline', type: 'string', label: 'CTA Headline' },
          { name: 'ctaSubtext', type: 'string', label: 'CTA Subtext' },
        ],
      },
      {
        name: 'estimatePage',
        label: 'Estimate Page',
        path: 'content/pages',
        format: 'json',
        match: { include: 'estimate' },
        ui: { allowedActions: { create: false, delete: false }, router: () => '/instant-estimate' },
        fields: [
          { name: 'heroHeadline', type: 'string', label: 'Hero Headline' },
          { name: 'heroSubtext', type: 'string', label: 'Hero Subtext' },
          { name: 'secondStoreySurcharge', type: 'number', label: 'Second Storey Surcharge ($)' },
          faqListField,
        ],
      },
      {
        name: 'gallery',
        label: 'Gallery',
        path: 'content/gallery',
        format: 'json',
        fields: [
          { name: 'src', type: 'image', label: 'Image' },
          { name: 'alt', type: 'string', label: 'Alt Text' },
          { name: 'category', type: 'string', label: 'Category', options: [
            { value: 'retrofit', label: 'Retrofit Glazing' },
            { value: 'commercial', label: 'Commercial' },
            { value: 'shopfronts', label: 'Shopfronts' },
            { value: 'repairs', label: 'Repairs' },
          ]},
          { name: 'caption', type: 'string', label: 'Caption' },
          { name: 'order', type: 'number', label: 'Display Order' },
        ],
      },
      {
        name: 'pricingOption',
        label: 'Pricing Options',
        path: 'content/pricing',
        format: 'json',
        fields: [
          { name: 'optionKey', type: 'string', label: 'Option Key (A/B/C/D)' },
          { name: 'label', type: 'string', label: 'Label' },
          { name: 'sublabel', type: 'string', label: 'Sublabel' },
          { name: 'spec', type: 'string', label: 'Glass Spec' },
          { name: 'pricePerSqm', type: 'number', label: 'Price per m²' },
          { name: 'heatPct', type: 'number', label: 'Heat Reduction %' },
          { name: 'noisePct', type: 'number', label: 'Noise Reduction %' },
          { name: 'tech', type: 'object', label: 'Technical Details', fields: [
            { name: 'composition', type: 'string', list: true, label: 'Composition' },
            { name: 'spacerMm', type: 'number', label: 'Spacer (mm)' },
            { name: 'lowE', type: 'boolean', label: 'Low-E Coating' },
            { name: 'acousticPVB', type: 'boolean', label: 'Acoustic PVB' },
            { name: 'tinted', type: 'boolean', label: 'Tinted' },
            { name: 'bestFor', type: 'string', label: 'Best For' },
            { name: 'rwRating', type: 'string', label: 'Rw Rating' },
            { name: 'notes', type: 'string', label: 'Notes', ui: { component: 'textarea' } },
          ]},
        ],
      },
    ],
  },
})
